notARepository: "quit"
os:
  editPreset: nvim

git:
  paging:
    colorArg: always
    useConfig: true

gui:
  showBottomLine: false
  theme:
    activeBorderColor:
      - green
      - bold
    selectedLineBgColor:
      - black
    unstagedChangesColor:
      - yellow
  border: rounded
  nerdFontsVersion: "3"
