import = ["~/.config/alacritty/tokyonight_storm.toml"]

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

# [shell]
# program = "/usr/bin/sh"
# args = ["-l", "-c", "tmux"]

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"
style = { blinking = "On", shape = "Beam" }

[font]
size = 12.0
builtin_box_drawing = true
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[hints]
alphabet = "jfkdls;ahgurieowpq"

# URLs
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }

# Hash
[[hints.enabled]]
action = "Paste"
post_processing = true
regex = "[a-f0-9]{40}|[a-f0-9]{7,}"
binding = { key = "H", mods = "Control|Shift" }
mouse = { enabled = true, mods = "None" }

# Line
[[hints.enabled]]
action = "Select"
post_processing = true
regex = "[[[:ascii:]]]{8,}"
binding = { key = "L", mods = "Control|Shift" }

# Path
[[hints.enabled]]
action = "Select"
post_processing = true
regex = "(/?[^/ \"']*[a-zA-Z0-9][^/ \"':]*/([^/ \"']+/?)*)|(/[^/ \"']*[a-zA-Z0-9][^/ \"']*)"
binding = { key = "P", mods = "Control|Shift" }

# Jump
[[hints.enabled]]
action = "MoveViModeCursor"
regex = "[[[:ascii:]]&&[[:^blank:]]]{2,}"
binding = { key = "J", mods = "Control|Shift" }

# username/project
[[hints.enabled]]
action = "Copy"
post_processing = true
regex = '([\w\d]{1}[-\w\d]+)(/){1}([-\w\d\.]+)'
binding = { key = "G", mods = "Control|Shift" }
mouse = { enabled = true, mods = "None" }
command = { program = "brave", args = "--incognito" }

# Issue or Pull Request number
[[hints.enabled]]
action = "Copy"
post_processing = true
regex = "#[0-9]+"
binding = { key = "I", mods = "Control|Shift" }
mouse = { mods = "None", enabled = true }

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
    { key = "Q", action = "ToggleViMode", mode = "Vi" },
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
    # { key = "L", mods = "Control|Alt", action = "ClearLogNotice" },

    { key = "I", mods = "Control", chars = "\u001B[105;5u" },
    { key = "J", mods = "Control|Shift", chars = "\u001B[74;6u" },
    { key = "K", mods = "Control|Shift", chars = "\u001B[75;6u" },
    { key = "L", mods = "Control|Shift", chars = "\u001B[76;6u" },
    { key = "H", mods = "Control|Shift", chars = "\u001B[72;6u" },

    { key = "Return", mods = "Shift", chars = "\u001B[13;2u" },
    { key = "Return", mods = "Control", chars = "\u001B[13;5u" },
    { key = "Period", mods = "Control", chars = "\u001B[46;5u" },
    { key = "Comma", mods = "Control", chars = "\u001B[44;5u" },
    { key = "Semicolon", mods = "Control", chars = "\u001B[59;5u" },
]

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[window]
blur = true
resize_increments = true
decorations = "None"
decorations_theme_variant = "Dark"
dynamic_padding = false
padding = { x = 0, y = 0 }
opacity = 1.0                               # making opaque otherwise some highlight looks different in nvim

[debug]
renderer = "glsl3"
# highlight_damage = true
